services:
  app1:
    build: .
    image: task-manager-api
    container_name: todo-api-1
    expose:
      - "8000"
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
      INSTANCE_ID: "1"

  app2:
    image: task-manager-api
    container_name: todo-api-2
    expose:
      - "8000"
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
      INSTANCE_ID: "2"
    depends_on:
      - app1

  app3:
    image: task-manager-api
    container_name: todo-api-3
    expose:
      - "8000"
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
      INSTANCE_ID: "3"
    depends_on:
      - app1

  nginx:
    image: nginx:1.27-alpine
    container_name: todo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    restart: unless-stopped
